// <auto-generated />
using System;
using OpenAudioOrchestrator.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OpenAudioOrchestrator.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329071228_AddVoiceLibraryAndGenerationLog")]
    partial class AddVoiceLibraryAndGenerationLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("OpenAudioOrchestrator.Web.Data.Entities.GenerationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceVoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelProfileId");

                    b.HasIndex("ReferenceVoiceId");

                    b.ToTable("GenerationLogs");
                });

            modelBuilder.Entity("OpenAudioOrchestrator.Web.Data.Entities.ModelProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckpointPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CudaAllocConf")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableHalf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageTag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ModelProfiles");
                });

            modelBuilder.Entity("OpenAudioOrchestrator.Web.Data.Entities.ReferenceVoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VoiceId")
                        .IsUnique();

                    b.ToTable("ReferenceVoices");
                });

            modelBuilder.Entity("OpenAudioOrchestrator.Web.Data.Entities.GenerationLog", b =>
                {
                    b.HasOne("OpenAudioOrchestrator.Web.Data.Entities.ModelProfile", "ModelProfile")
                        .WithMany()
                        .HasForeignKey("ModelProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenAudioOrchestrator.Web.Data.Entities.ReferenceVoice", "ReferenceVoice")
                        .WithMany()
                        .HasForeignKey("ReferenceVoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelProfile");

                    b.Navigation("ReferenceVoice");
                });
#pragma warning restore 612, 618
        }
    }
}
